### ISSUE TITLE
Why update configuration is unsupported?

### ISSUE THREAD

**Issue by SergeyLee** [RestComm/jain-slee.http#6]
HttpServletResourceAdaptor raConfigurationUpdate() method.

https://github.com/RestComm/jain-slee.http/blob/master/resources/http-servlet/ra/src/main/java/org/restcomm/slee/resource/http/HttpServletResourceAdaptor.java

**Comment by gfigiel** [comment]
Is there any update on this issue?

**Comment by yarel79** [comment]
As per the field description "the ra entity name, which matches the servlet name".  

Now consider three places:

1) WAR : https://github.com/RestComm/jain-slee.http/blob/master/resources/http-servlet/war/src/main/webapp/WEB-INF/web.xml#L15-L24
2) Common : https://github.com/RestComm/jain-slee.http/blob/master/resources/http-servlet/common/src/main/java/org/restcomm/slee/resource/http/HttpServletRaServlet.java#L53
3) RA : https://github.com/RestComm/jain-slee.http/blob/master/resources/http-servlet/ra/src/main/java/org/restcomm/slee/resource/http/HttpServletResourceAdaptor.java#L145-L148

I think unsupported operation means, that name change is not supported, since chaning name of RA would introduce mismatch with 2) (Or one would have to change servlet name in runtime too :), well or at least handle it differently ).

I suppose name change shouldn't be supported, but there can be another property introduced for the RA:

https://github.com/RestComm/jain-slee.http/blob/master/resources/http-servlet/ra/src/main/java/org/restcomm/slee/resource/http/HttpServletResourceAdaptor.java#L466

Why to hardcode 15000 ms as a timeout? Perhaps there should be another entry defined to have this parameter configurable and by this chance, to change raConfigurationUpdate() to throw exception only if "name" is tried to be updated.

**Comment by deruelle** [comment]
@SergeyLee any updates here ?

**Comment by nhanth87** [comment]
Just read the code of http-client ra, 
 I think it's not difficult to have support re-config and it's good that we will never need restart jainslee for update deploy-config.xml

**Comment by deruelle** [comment]
@nhanth87 do you want to take a crack at it and do a PR ?

**Comment by satanatoly** [comment]
implemented configuration update support, closing
